<%@ Page Title="" Language="C#" MasterPageFile="~/Company/Company.Master" AutoEventWireup="true" CodeBehind="PostedJobs.aspx.cs" Inherits="Empleo.Company.PostedJobs" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            height: 557px;
        }
        .auto-style2 {
            margin-left: 106px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   
    <div class="auto-style1" style="background-image: url('img/Bghome2.jpg')">
        &nbsp;&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="27px" Text="Posted Jobs"></asp:Label>
        <br />
&nbsp;<asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" OnPageIndexChanging="DetailsView1_PageIndexChanging" OnItemUpdating="DetailsView1_Updating" OnItemDeleting="DetailsView1_Deleting" OnModeChanging="DetailsView1_ModeChanging" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateRows="False" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" CssClass="auto-style2" DataKeyNames="Job_Id,Post_Name,Category,Job_Location,Experience,Salary,Qualification,Skills,Posted_Date,Status" GridLines="Vertical" HeaderText="Jobs Posted" Height="100px" Width="300px">
            <AlternatingRowStyle BackColor="#DCDCDC" />
            <EditRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <Fields>
                <asp:BoundField DataField="Job_Id" HeaderText="Job Id" ReadOnly="true" />
                <asp:BoundField DataField="Post_Name" HeaderText="Post Name" />
                <asp:BoundField DataField="Category" HeaderText="Category" />
                <asp:BoundField DataField="Job_Location" HeaderText="Location" />
                <asp:BoundField DataField="Experience" HeaderText="Experience" />
                <asp:BoundField DataField="Salary" HeaderText="Salary" />
                <asp:BoundField DataField="Qualification" HeaderText="Qualification" />
                <asp:BoundField DataField="Skills" HeaderText="Skills" />
                <asp:BoundField DataField="Posted_Date" HeaderText="Posted Date" />
                <asp:BoundField DataField="Status" HeaderText="Status" />
            </Fields>
            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" Font-Size="X-Large" ForeColor="White" HorizontalAlign="Center" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
        </asp:DetailsView>
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:HiddenField ID="Hidid" runat="server" Value="-1" />

        <asp:HiddenField ID="HiddenField1" runat="server" />
    </div>
   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
   
</asp:Content>
